clc 
clear
t = 0:0.001:10;
x1 = zeros(size(t));
x2 = zeros(size(t));
x1((t>=3)&(t<=6))=1;
x2((t>=2)&(t<=5))= 3;
subplot(3,2,1);
plot(t,x1);
xlabel('time');
ylabel('amplitude');
ylim([0,3]);
title('x1');
subplot(3,2,2);
plot(t,x2);
xlabel('time');
ylabel('amplitude');
ylim([0,5]);
title('x2');
a = x1 + x2;
subplot(3,2,3);
plot(t,a);
xlabel('time');
ylabel('amplitude');
ylim([0,5]);
title('addition');
b = x1 - x2;
subplot(3,2,4);
plot(t,b);
xlabel('time');
ylabel('amplitude');
ylim([-5,5]);
title('subtraction');
c = x1.*x2;
subplot(3,2,5);
plot(t,c);
xlabel('time');
ylabel('amplitude');
ylim([-10,10]);
title('multiplication');