clc 
clear
t = 0:0.001:10;
x1 = zeros(size(t));
x2 = zeros(size(t));
x1((t>=3)&(t<=6))=1;
x2((t>=2)&(t<=5))= 3;
subplot(3,3,1);
plot(t,x1);
xlabel('time');
ylabel('amplitude');
ylim([0,3]);
title('x1');
subplot(3,3,2);
plot(t,x2);
xlabel('time');
ylabel('amplitude');
ylim([0,5]);
title('x2');
a = x1 + x2;
subplot(3,3,3);
plot(t,a);
xlabel('time');
ylabel('amplitude');
ylim([0,5]);
title('addition');
trev = -t;
subplot(3,3,4);
plot(trev , a);
xlabel('time');
ylabel('amplitude');
ylim([0,5]);
title('time reversal');
tadv = t-2;
subplot(3,3,5);
plot(tadv , a);
xlabel('time');
ylabel('amplitude');
ylim([0,5]);
title('time advance');
tdel = t+2;
subplot(3,3,6);
plot(tdel , a);
xlabel('time');
ylabel('amplitude');
ylim([0,5]);
title('time delay');
texp = 2*t;
subplot(3,3,7);
plot(texp , a);
xlabel('time');
ylabel('amplitude');
ylim([0,5]);
title('time expansion');
tcomp = 0.5*t;
subplot(3,3,8);
plot(trev , a);
xlabel('time');
ylabel('amplitude');
ylim([0,5]);
title('time compression');
